apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-app
  template:
    metadata:
      labels:
        app: fe-app
    spec:
      containers:
        - name: fe-container
          image: cr.yandex/crpf0ksoueue60lg97jm/fe
          startupProbe:
            httpGet:
              port: 3000
              path: /
            failureThreshold: 30
            periodSeconds: 10