version: "3.4"

services:
  db:
    image: postgres:13-alpine
    container_name: remains_db
    environment:
      - POSTGRES_DB=remains-dev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - db-data:/var/lib/postgresql/data-remains:rw
    ports:
      - "5432:5432"

volumes:
  db-data: {}
