FROM node:16.13.0-alpine
COPY ["package.json", "package-lock.json*", "./"]
RUN apt-get install gcc
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build
RUN npm run copy-env
CMD ["npm", "run", "start:prod", "-p", "8080"]
