name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  OAUTH_DOCKER: AQAAAAAM5fwgAATuwc-Y_W32pU11sWdj3ACgcVM
  CLUSTER_URL: https://62.84.124.164
  SERVICE_ACC_API_KEY: AQVN2ie2khFWrx0H1IIEPyCXMRHYHNr958DcgslR
  REGISTRY_ID: crpf0ksoueue60lg97jm
  DEPLOYMENT_NAME: frontend

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login
        run: |-
          docker login -u oauth -p $OAUTH_DOCKER cr.yandex

      - name: Build docker image
        run: |-
          docker build -t cr.yandex/$REGISTRY_ID/fe/fe:latest -f dockerfile ./fe

      - name: Push docker image
        run: |-
          docker push cr.yandex/$REGISTRY_ID/fe/fe:latest

#      - name: Run in kubernetes cluster
#        run: |-
#          kubectl run --attach fe --image cr.yandex/${REGISTRY_ID}/fe/fe:latest
#
#      - name: Pull docker in Kub
#        run: |-
#          docker pull cr.yandex/${REGISTRY_ID}/fe
#
#      - name: Run docker container in Kub
#        run: |-
#          docker run cr.yandex/$REGISTRY_ID/fe/fe:latest

      - name: Deploy to kubernetes
        run: |-
          kubectl config set-cluster cluster --server="$CLUSTER_URL" --insecure-skip-tls-verify=true
          kubectl config set-credentials service-account --token="$SERVICE_ACC_API_KEY"
          kubectl config set-context default --cluster=cluster --user=service-account
          kubectl config use-context default
          kubectl run --attach fe --image cr.yandex/${REGISTRY_ID}/fe/fe:latest



#     !!!!! УДАЛЯТЬ СТАРЫЕ ОБРАЗЫ, ИНАЧЕ ОНИ ПЛОДЯТСЯ