name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY_ID: crpf0ksoueue60lg97jm
  OAUTH_DOCKER: AQAAAAAM5fwgAATuwc-Y_W32pU11sWdj3ACgcVM
  # SA_TOKEN: get here https://cloud.yandex.ru/docs/managed-kubernetes/operations/connect/create-static-conf

jobs:
  be-deploy:
    name: BE Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login
        run: |-
          docker login -u oauth -p $OAUTH_DOCKER cr.yandex

      - name: Build docker images
        run: |-
          docker build ./be -f be/dockerfile -t cr.yandex/$REGISTRY_ID/be:${{ github.sha }} -t cr.yandex/$REGISTRY_ID/be:latest

      - name: Push docker images
        run: |-
          docker push cr.yandex/$REGISTRY_ID/be --all-tags

#     https://nicwortel.nl/blog/2022/05/27/continuous-deployment-to-kubernetes-with-github-actions
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests:  |
            deploy/be-deployment.yaml
            deploy/be-service.yaml
            deploy/ingress.yaml
          images: |
            cr.yandex/crpf0ksoueue60lg97jm/be:${{ github.sha }}
  fe-deploy:
    name: FE Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
          cache: 'npm'
          cache-dependency-path: fe/package-lock.json

      - name: Install
        working-directory: fe
        run: npm ci

      - name: Docker login
        run: |-
          docker login -u oauth -p $OAUTH_DOCKER cr.yandex

      - name: Build docker images
        run: |-
          docker build ./fe -f fe/dockerfile -t cr.yandex/$REGISTRY_ID/fe:${{ github.sha }} -t cr.yandex/$REGISTRY_ID/fe:latest

      - name: Push docker images
        run: |-
          docker push cr.yandex/$REGISTRY_ID/fe --all-tags

      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            deploy/fe-deployment.yaml
            deploy/fe-service.yaml
            deploy/ingress.yaml
          images: |
            cr.yandex/crpf0ksoueue60lg97jm/fe:${{ github.sha }}