name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY_ID: crpf0ksoueue60lg97jm
  OAUTH_DOCKER: AQAAAAAM5fwgAATuwc-Y_W32pU11sWdj3ACgcVM
  # SA_TOKEN: get here https://cloud.yandex.ru/docs/managed-kubernetes/operations/connect/create-static-conf

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login
        run: |-
          docker login -u oauth -p $OAUTH_DOCKER cr.yandex

      - name: Build docker image
        run: |-
          docker build  -f dockerfile ./fe -t cr.yandex/$REGISTRY_ID/fe:${{ github.sha }} -t cr.yandex/$REGISTRY_ID/fe:latest

      - name: Push docker image
        run: |-
          docker push cr.yandex/$REGISTRY_ID/fe --all-tags

#     https://nicwortel.nl/blog/2022/05/27/continuous-deployment-to-kubernetes-with-github-actions
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests:  |
            deploy/fe-deployment.yaml
            deploy/ingress.yaml
            deploy/fe-service.yaml
          images: |
            cr.yandex/crpf0ksoueue60lg97jm/fe:${{ github.sha }}