name: Linter and build

on:
  pull_request:
    types: [opened, reopened]

jobs:
  linter-and-test-build:
    name: "Build test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.9.0'
          cache: 'npm'

      - name: Install packages
        run: npm ci
      
      - name: Build
        run: npm run build